import { DatePipe, NgTemplateOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, TemplateRef, computed, contentChild, input, output, signal } from '@angular/core';
import { JSeverity } from 'jrng-ui/core';

export type JAuditLogLayout = 'timeline' | 'table' | 'compact';
export interface JAuditLogEntry<T = unknown> { readonly id: string | number; readonly actor?: string; readonly avatar?: string; readonly action: string; readonly entity?: string; readonly timestamp: Date | string | number; readonly before?: unknown; readonly after?: unknown; readonly metadata?: T; readonly severity?: JSeverity; readonly status?: string; }

@Component({
  selector: 'j-audit-log', imports:[DatePipe,NgTemplateOutlet],
  template:`<section class="j-audit-log" [attr.data-j-layout]="layout()">
    <div class="j-audit-log__filters"><input type="search" [value]="search()" (input)="search.set(valueOf($event))" [attr.aria-label]="searchLabel()" /> <ng-content select="[jAuditLogFilters]" /></div>
    @if(loading()){<p role="status">Loading audit history...</p>}@else if(error()){<p role="alert">{{error()}}</p>}@else if(!filtered().length){<p>{{emptyMessage()}}</p>}@else if(layout()==='table'){
      <div class="j-audit-log__table-wrap"><table><thead><tr><th>Actor</th><th>Action</th><th>Entity</th><th>Timestamp</th><th></th></tr></thead><tbody>@for(item of pageItems();track item.id){<tr><td>{{item.actor}}</td><td>{{item.action}}</td><td>{{item.entity}}</td><td>{{item.timestamp|date:'medium'}}</td><td><button type="button" (click)="toggle(item.id)" [attr.aria-expanded]="expanded().has(item.id)">Details</button></td></tr>@if(expanded().has(item.id)){<tr><td colspan="5"><pre>{{details(item)}}</pre></td></tr>}}</tbody></table></div>
    }@else{<ol class="j-audit-log__list">@for(item of pageItems();track item.id){<li><article><div class="j-audit-log__heading">@if(item.avatar){<img [src]="item.avatar" alt="" loading="lazy"/>}<strong>{{item.actor||'System'}}</strong> {{item.action}} @if(item.entity){<span>{{item.entity}}</span>}</div><time>{{item.timestamp|date:'medium'}}</time>@if(itemTemplate();as template){<ng-container [ngTemplateOutlet]="template" [ngTemplateOutletContext]="{$implicit:item}"/>}@else if(item.before!==undefined||item.after!==undefined||item.metadata){<button type="button" (click)="toggle(item.id)" [attr.aria-expanded]="expanded().has(item.id)">Details</button>@if(expanded().has(item.id)){<pre>{{details(item)}}</pre>}}</article></li>}</ol>}
    @if(filtered().length>pageSize()){<nav aria-label="Audit pagination"><button type="button" [disabled]="page()===0" (click)="page.set(page()-1)">Previous</button><button type="button" [disabled]="(page()+1)*pageSize()>=filtered().length" (click)="page.set(page()+1)">Next</button></nav>}
    @if(lazy()){<button type="button" (click)="loadMore.emit()">Load more</button>}
  </section>`,
  styles:[`.j-audit-log{display:grid;gap:var(--j-spacing-3)}.j-audit-log__filters{display:flex;gap:var(--j-spacing-2)}.j-audit-log__list{display:grid;gap:var(--j-spacing-3);list-style:none;margin:0;padding:0}.j-audit-log__list article{border-inline-start:3px solid var(--j-color-border);padding:var(--j-spacing-3)}.j-audit-log__heading{display:flex;align-items:center;gap:var(--j-spacing-2)}img{border-radius:50%;height:2rem;width:2rem}time{color:var(--j-color-muted-foreground);font-size:var(--j-font-size-sm)}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid var(--j-color-border);padding:var(--j-spacing-2);text-align:start}.j-audit-log__table-wrap{overflow:auto}pre{overflow:auto;white-space:pre-wrap}`], changeDetection:ChangeDetectionStrategy.OnPush
})
export class JAuditLogComponent<T=unknown>{readonly items=input<readonly JAuditLogEntry<T>[]>([]);readonly layout=input<JAuditLogLayout>('timeline');readonly loading=input(false);readonly error=input('');readonly emptyMessage=input('No audit history.');readonly searchLabel=input('Search audit history');readonly pageSize=input(20);readonly lazy=input(false);readonly loadMore=output<void>();readonly itemTemplate=contentChild<unknown,TemplateRef<unknown>>('jAuditLogItem',{read:TemplateRef});readonly search=signal('');readonly page=signal(0);readonly expanded=signal(new Set<string|number>());readonly filtered=computed(()=>{const q=this.search().trim().toLocaleLowerCase();return q?this.items().filter(x=>`${x.actor} ${x.action} ${x.entity} ${x.status}`.toLocaleLowerCase().includes(q)):this.items();});readonly pageItems=computed(()=>this.filtered().slice(this.page()*this.pageSize(),(this.page()+1)*this.pageSize()));valueOf(e:Event){return (e.target as HTMLInputElement).value;}toggle(id:string|number){this.expanded.update(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n;});}details(i:JAuditLogEntry<T>){return JSON.stringify({before:i.before,after:i.after,metadata:i.metadata},null,2);}}
