import { JThemePreset } from '../preset.types';

/**
 * JRNG UI's original balanced visual identity for general-purpose products.
 * Values are authored for JRNG and shared by the static CSS default theme.
 */
export const defaultPreset: JThemePreset = {
  id: 'default',
  name: 'default',
  displayName: 'Default',
  primitive: {
    '--j-font-family':
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    '--j-font-size-xs': '0.75rem',
    '--j-font-size-sm': '0.875rem',
    '--j-font-size-md': '1rem',
    '--j-font-size-lg': '1.125rem',
    '--j-font-size-xl': '1.35rem',
    '--j-font-size-2xl': '2rem',
    '--j-font-weight-normal': '400',
    '--j-font-weight-medium': '550',
    '--j-font-weight-semibold': '650',
    '--j-font-weight-bold': '700',
    '--j-line-height-tight': '1.2',
    '--j-line-height-normal': '1.5',
    '--j-line-height-relaxed': '1.65',
    '--j-spacing-1': '0.25rem',
    '--j-spacing-2': '0.5rem',
    '--j-spacing-3': '0.75rem',
    '--j-spacing-4': '1rem',
    '--j-spacing-5': '1.25rem',
    '--j-spacing-6': '1.5rem',
    '--j-spacing-8': '2rem',
    '--j-radius-xs': '0.25rem',
    '--j-radius-sm': '0.375rem',
    '--j-radius-md': '0.5rem',
    '--j-radius-lg': '0.75rem',
    '--j-radius-xl': '1rem',
    '--j-radius-full': '999px',
    '--j-shadow-xs': '0 1px 1px rgb(15 23 42 / 5%)',
    '--j-shadow-sm': '0 1px 2px rgb(15 23 42 / 8%), 0 1px 1px rgb(15 23 42 / 4%)',
    '--j-shadow-md': '0 10px 24px rgb(15 23 42 / 10%), 0 2px 6px rgb(15 23 42 / 6%)',
    '--j-shadow-lg': '0 22px 60px rgb(15 23 42 / 14%)',
    '--j-duration-instant': '0ms',
    '--j-duration-fast': '120ms',
    '--j-duration-normal': '180ms',
    '--j-duration-slow': '260ms',
    '--j-ease-standard': 'cubic-bezier(0.2, 0, 0, 1)',
    '--j-ease-emphasized': 'cubic-bezier(0.2, 0, 0, 1.2)',
    '--j-density-gap': 'var(--j-spacing-2)',
    '--j-density-padding': 'var(--j-spacing-3)',
  },
  semantic: {
    '--j-color-on-primary': 'var(--j-color-primary-foreground)',
    '--j-color-on-danger': 'var(--j-color-danger-foreground)',
    '--j-focus-ring': '0 0 0 3px var(--j-color-ring)',
    '--j-shadow-focus': 'var(--j-focus-ring)',
    '--j-disabled-opacity': '0.58',
    '--j-selection-color': 'var(--j-color-primary)',
    '--j-selection-background': 'var(--j-color-primary-soft)',
  },
  light: {
    '--j-color-background': '#f7f9fc',
    '--j-color-page': 'var(--j-color-background)',
    '--j-color-foreground': '#172033',
    '--j-color-text': 'var(--j-color-foreground)',
    '--j-color-text-muted': '#647087',
    '--j-color-text-soft': '#8b96aa',
    '--j-color-muted': '#eef2f7',
    '--j-color-muted-foreground': 'var(--j-color-text-muted)',
    '--j-color-card': '#ffffff',
    '--j-color-card-foreground': 'var(--j-color-foreground)',
    '--j-color-popover': '#ffffff',
    '--j-color-popover-foreground': 'var(--j-color-foreground)',
    '--j-color-surface': 'var(--j-color-card)',
    '--j-color-surface-elevated': 'var(--j-color-popover)',
    '--j-color-surface-muted': 'var(--j-color-muted)',
    '--j-color-surface-subtle': '#f3f6fa',
    '--j-color-border': '#d8e0ea',
    '--j-color-border-strong': '#bdc8d7',
    '--j-color-input': 'var(--j-color-border)',
    '--j-color-primary': '#4f46e5',
    '--j-color-primary-hover': '#4338ca',
    '--j-color-primary-active': '#3730a3',
    '--j-color-primary-soft': '#eef0ff',
    '--j-color-primary-foreground': '#ffffff',
    '--j-color-secondary': '#293348',
    '--j-color-secondary-hover': '#1d2638',
    '--j-color-secondary-soft': '#e8edf4',
    '--j-color-secondary-foreground': '#ffffff',
    '--j-color-success': '#087f5b',
    '--j-color-success-soft': '#e7f8f1',
    '--j-color-success-foreground': '#ffffff',
    '--j-color-info': '#087bb8',
    '--j-color-info-soft': '#e7f5fc',
    '--j-color-info-foreground': '#ffffff',
    '--j-color-warning': '#b86500',
    '--j-color-warning-soft': '#fff4dc',
    '--j-color-warning-foreground': '#2a1900',
    '--j-color-danger': '#c92a2a',
    '--j-color-danger-soft': '#fff0f0',
    '--j-color-danger-foreground': '#ffffff',
    '--j-color-neutral': '#5f6b7e',
    '--j-color-neutral-soft': '#edf1f6',
    '--j-color-neutral-foreground': '#ffffff',
    '--j-color-contrast': '#101827',
    '--j-color-contrast-soft': '#dfe5ed',
    '--j-color-contrast-foreground': '#ffffff',
    '--j-color-ring': 'rgb(79 70 229 / 30%)',
    '--j-color-hover-background': '#edf1f7',
    '--j-color-selected-background': '#e9eaff',
    '--j-color-highlight': '#895f00',
    '--j-color-highlight-background': '#fff0b8',
    '--j-color-disabled-background': '#eef1f5',
    '--j-color-disabled-text': '#929cad',
    '--j-overlay-backdrop-bg': 'rgb(15 23 42 / 54%)',
  },
  dark: {
    '--j-color-background': '#0c1220',
    '--j-color-page': 'var(--j-color-background)',
    '--j-color-foreground': '#edf2fa',
    '--j-color-text': 'var(--j-color-foreground)',
    '--j-color-text-muted': '#a7b1c2',
    '--j-color-text-soft': '#778399',
    '--j-color-muted': '#182235',
    '--j-color-muted-foreground': 'var(--j-color-text-muted)',
    '--j-color-card': '#121b2c',
    '--j-color-card-foreground': 'var(--j-color-foreground)',
    '--j-color-popover': '#172237',
    '--j-color-popover-foreground': 'var(--j-color-foreground)',
    '--j-color-surface': 'var(--j-color-card)',
    '--j-color-surface-elevated': 'var(--j-color-popover)',
    '--j-color-surface-muted': 'var(--j-color-muted)',
    '--j-color-surface-subtle': '#1d293d',
    '--j-color-border': '#2b3850',
    '--j-color-border-strong': '#465570',
    '--j-color-input': '#384761',
    '--j-color-primary': '#9298ff',
    '--j-color-primary-hover': '#adb1ff',
    '--j-color-primary-active': '#c9cbff',
    '--j-color-primary-soft': '#292d68',
    '--j-color-primary-foreground': '#10133a',
    '--j-color-secondary': '#dce4ef',
    '--j-color-secondary-hover': '#f4f7fb',
    '--j-color-secondary-soft': '#253147',
    '--j-color-secondary-foreground': '#111827',
    '--j-color-success': '#4ed2a2',
    '--j-color-success-soft': '#123f35',
    '--j-color-success-foreground': '#05271f',
    '--j-color-info': '#55c2f3',
    '--j-color-info-soft': '#123f58',
    '--j-color-info-foreground': '#072d42',
    '--j-color-warning': '#ffc45b',
    '--j-color-warning-soft': '#503a12',
    '--j-color-warning-foreground': '#2d1c00',
    '--j-color-danger': '#ff8585',
    '--j-color-danger-soft': '#522528',
    '--j-color-danger-foreground': '#360b0d',
    '--j-color-neutral': '#c0cada',
    '--j-color-neutral-soft': '#263247',
    '--j-color-neutral-foreground': '#101827',
    '--j-color-contrast': '#ffffff',
    '--j-color-contrast-soft': '#344159',
    '--j-color-contrast-foreground': '#101827',
    '--j-color-ring': 'rgb(146 152 255 / 38%)',
    '--j-color-hover-background': '#202d43',
    '--j-color-selected-background': '#2a3167',
    '--j-color-highlight': '#ffd980',
    '--j-color-highlight-background': '#5a4112',
    '--j-color-disabled-background': '#202b3e',
    '--j-color-disabled-text': '#69768b',
    '--j-overlay-backdrop-bg': 'rgb(2 6 18 / 68%)',
    '--j-shadow-xs': '0 1px 1px rgb(0 0 0 / 30%)',
    '--j-shadow-sm': '0 2px 5px rgb(0 0 0 / 32%)',
    '--j-shadow-md': '0 14px 34px rgb(0 0 0 / 38%)',
    '--j-shadow-lg': '0 28px 72px rgb(0 0 0 / 48%)',
  },
  components: {
    control: {
      '--j-control-height-sm': '2rem',
      '--j-control-height-md': '2.5rem',
      '--j-control-height-lg': '3rem',
      '--j-control-padding-x-sm': 'var(--j-spacing-3)',
      '--j-control-padding-x-md': 'var(--j-spacing-4)',
      '--j-control-padding-x-lg': 'var(--j-spacing-5)',
      '--j-control-radius': 'var(--j-radius-md)',
      '--j-control-bg': 'var(--j-color-card)',
      '--j-control-color': 'var(--j-color-card-foreground)',
      '--j-control-border-color': 'var(--j-color-input)',
      '--j-control-placeholder-color': 'var(--j-color-text-muted)',
      '--j-control-focus-ring': 'var(--j-focus-ring)',
    },
    button: {
      '--j-button-height-sm': 'var(--j-control-height-sm)',
      '--j-button-height-md': 'var(--j-control-height-md)',
      '--j-button-height-lg': 'var(--j-control-height-lg)',
      '--j-button-radius': 'var(--j-control-radius)',
      '--j-button-font-weight': 'var(--j-font-weight-semibold)',
      '--j-button-primary-bg': 'var(--j-color-primary)',
      '--j-button-primary-bg-hover': 'var(--j-color-primary-hover)',
      '--j-button-primary-color': 'var(--j-color-primary-foreground)',
      '--j-button-secondary-bg': 'var(--j-color-secondary)',
      '--j-button-secondary-color': 'var(--j-color-secondary-foreground)',
      '--j-button-outline-border-color': 'var(--j-color-border)',
      '--j-button-ghost-bg-hover': 'var(--j-color-hover-background)',
    },
    input: {
      '--j-input-height-sm': 'var(--j-control-height-sm)',
      '--j-input-height-md': 'var(--j-control-height-md)',
      '--j-input-height-lg': 'var(--j-control-height-lg)',
      '--j-input-radius': 'var(--j-control-radius)',
      '--j-input-bg': 'var(--j-control-bg)',
      '--j-input-text-color': 'var(--j-control-color)',
      '--j-input-border-color': 'var(--j-control-border-color)',
      '--j-input-hover-border-color': 'var(--j-color-border-strong)',
      '--j-input-focus-border-color': 'var(--j-color-primary)',
      '--j-input-focus-shadow-color': 'var(--j-color-ring)',
      '--j-input-placeholder-color': 'var(--j-control-placeholder-color)',
      '--j-input-helper-color': 'var(--j-color-text-muted)',
      '--j-input-error-color': 'var(--j-color-danger)',
      '--j-input-success-color': 'var(--j-color-success)',
      '--j-input-warning-color': 'var(--j-color-warning)',
      '--j-input-disabled-bg': 'var(--j-color-disabled-background)',
    },
    select: {
      '--j-select-bg': 'var(--j-control-bg)',
      '--j-select-color': 'var(--j-control-color)',
      '--j-select-border-color': 'var(--j-control-border-color)',
      '--j-select-option-hover-bg': 'var(--j-color-hover-background)',
      '--j-select-option-selected-bg': 'var(--j-color-selected-background)',
      '--j-select-overlay-radius': 'var(--j-radius-lg)',
    },
    card: {
      '--j-card-bg': 'var(--j-color-card)',
      '--j-card-color': 'var(--j-color-card-foreground)',
      '--j-card-border-color': 'var(--j-color-border)',
      '--j-card-radius': 'var(--j-radius-lg)',
      '--j-card-shadow': 'var(--j-shadow-sm)',
      '--j-card-padding': 'var(--j-spacing-5)',
    },
    dialog: {
      '--j-dialog-bg': 'var(--j-color-popover)',
      '--j-dialog-color': 'var(--j-color-popover-foreground)',
      '--j-dialog-border-color': 'var(--j-color-border)',
      '--j-dialog-radius': 'var(--j-radius-xl)',
      '--j-dialog-shadow': 'var(--j-shadow-lg)',
      '--j-dialog-padding': 'var(--j-spacing-4)',
    },
    scheduler: {
      '--j-scheduler-bg': 'var(--j-color-card)',
      '--j-scheduler-border-color': 'var(--j-color-border)',
      '--j-scheduler-header-bg': 'var(--j-color-surface-subtle)',
      '--j-scheduler-resource-rail-bg': 'var(--j-color-card)',
      '--j-scheduler-today-bg':
        'color-mix(in srgb, var(--j-color-primary) 7%, var(--j-color-card))',
      '--j-scheduler-selection-bg': 'var(--j-color-selected-background)',
      '--j-scheduler-business-bg': 'var(--j-color-card)',
      '--j-scheduler-non-business-bg': 'var(--j-color-surface-subtle)',
      '--j-scheduler-blocked-bg': 'var(--j-color-danger-soft)',
      '--j-scheduler-now-color': 'var(--j-color-danger)',
      '--j-scheduler-invalid-color': 'var(--j-color-danger)',
      '--j-scheduler-drag-shadow': 'var(--j-shadow-lg)',
      '--j-scheduler-row-height': '3.25rem',
      '--j-scheduler-overlay-bg': 'var(--j-color-popover)',
    },
    table: {
      '--j-table-bg': 'var(--j-color-card)',
      '--j-table-color': 'var(--j-color-card-foreground)',
      '--j-table-border-color': 'var(--j-color-border)',
      '--j-table-header-bg': 'var(--j-color-muted)',
      '--j-table-header-color': 'var(--j-color-text-muted)',
      '--j-table-header-font-weight': 'var(--j-font-weight-medium)',
      '--j-table-filter-row-bg': 'var(--j-color-surface-subtle)',
      '--j-table-filter-control-bg': 'var(--j-color-surface)',
      '--j-table-filter-control-border': 'var(--j-color-border)',
      '--j-table-filter-icon-color': 'var(--j-color-text-muted)',
      '--j-table-sort-icon-color': 'var(--j-color-text-soft)',
      '--j-table-sort-active-color': 'var(--j-color-primary)',
      '--j-table-frozen-bg': 'var(--j-color-card)',
      '--j-table-frozen-shadow-start': '0.25rem 0 0.35rem -0.35rem rgb(0 0 0 / 28%)',
      '--j-table-frozen-shadow-end': '-0.25rem 0 0.35rem -0.35rem rgb(0 0 0 / 28%)',
      '--j-table-pagination-bg': 'var(--j-color-card)',
      '--j-table-pagination-active-bg': 'var(--j-color-primary)',
      '--j-table-row-hover-bg': 'color-mix(in srgb, var(--j-color-primary) 6%, transparent)',
      '--j-table-selected-bg': 'var(--j-color-selected-background)',
      '--j-table-header-height': '2.625rem',
      '--j-table-filter-row-height': '3rem',
      '--j-table-row-height': '2.875rem',
      '--j-table-filter-control-height': '2.25rem',
      '--j-table-toolbar-height': '3rem',
      '--j-table-pagination-height': '2.875rem',
      '--j-table-cell-padding-x': 'var(--j-spacing-3)',
      '--j-table-cell-padding-y': 'var(--j-spacing-2)',
    },
    navigation: {
      '--j-menu-bg': 'var(--j-color-surface-elevated)',
      '--j-menu-color': 'var(--j-color-text)',
      '--j-menu-border-color': 'var(--j-color-border)',
      '--j-menu-item-hover-bg': 'var(--j-color-hover-background)',
      '--j-menu-item-height': '2.5rem',
      '--j-tabs-border-color': 'var(--j-color-border)',
      '--j-tabs-active-color': 'var(--j-color-primary)',
      '--j-tabs-hover-bg': 'var(--j-color-hover-background)',
    },
    feedback: {
      '--j-toast-bg': 'var(--j-color-surface-elevated)',
      '--j-toast-color': 'var(--j-color-text)',
      '--j-toast-border-color': 'var(--j-color-border)',
      '--j-toast-shadow': 'var(--j-shadow-md)',
      '--j-tooltip-bg': 'var(--j-color-foreground)',
      '--j-tooltip-color': 'var(--j-color-background)',
      '--j-tooltip-radius': 'var(--j-radius-sm)',
      '--j-skeleton-bg': 'var(--j-color-surface-subtle)',
      '--j-skeleton-shimmer-color': 'rgb(255 255 255 / 42%)',
    },
    overlay: {
      '--j-drawer-bg': 'var(--j-color-surface-elevated)',
      '--j-drawer-color': 'var(--j-color-text)',
      '--j-drawer-border-color': 'var(--j-color-border)',
      '--j-overlay-radius': 'var(--j-radius-xl)',
    },
    progress: {
      '--j-progress-track-bg': 'var(--j-color-muted)',
      '--j-progress-value-bg': 'var(--j-color-primary)',
    },
  },
  aliases: {
    '--j-color-focus': '--j-color-primary',
    '--j-input-color': '--j-input-text-color',
    '--j-highlight-background': '--j-color-highlight-background',
  },
};
