import { JThemePreset } from '../preset.types';
import { defaultPreset } from './default.preset';

/**
 * Original JRNG composition inspired by Material Design principles: structured
 * surfaces, purposeful elevation, clear state feedback, and deliberate motion.
 */
export const materialPreset: JThemePreset = {
  id: 'material',
  name: 'material',
  displayName: 'Material',
  primitive: {
    ...defaultPreset.primitive,
    '--j-font-family':
      "Roboto, Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif",
    '--j-font-weight-medium': '500',
    '--j-font-weight-semibold': '600',
    '--j-radius-xs': '0.125rem',
    '--j-radius-sm': '0.25rem',
    '--j-radius-md': '0.375rem',
    '--j-radius-lg': '0.5rem',
    '--j-radius-xl': '0.75rem',
    '--j-shadow-xs': '0 1px 2px rgb(22 26 36 / 12%)',
    '--j-shadow-sm': '0 2px 5px rgb(22 26 36 / 15%), 0 1px 2px rgb(22 26 36 / 10%)',
    '--j-shadow-md': '0 8px 18px rgb(22 26 36 / 17%), 0 3px 6px rgb(22 26 36 / 12%)',
    '--j-shadow-lg': '0 20px 42px rgb(22 26 36 / 22%), 0 7px 14px rgb(22 26 36 / 13%)',
    '--j-duration-fast': '100ms',
    '--j-duration-normal': '200ms',
    '--j-duration-slow': '300ms',
    '--j-ease-standard': 'cubic-bezier(0.22, 0, 0, 1)',
    '--j-ease-emphasized': 'cubic-bezier(0.3, 0, 0, 1.15)',
  },
  semantic: {
    ...defaultPreset.semantic,
    '--j-disabled-opacity': '0.52',
  },
  light: {
    ...defaultPreset.light,
    '--j-color-background': '#f5f6fa',
    '--j-color-foreground': '#20232c',
    '--j-color-text-muted': '#606673',
    '--j-color-text-soft': '#858b97',
    '--j-color-muted': '#eceef3',
    '--j-color-card-foreground': '#20232c',
    '--j-color-popover-foreground': '#20232c',
    '--j-color-surface-subtle': '#f0f1f5',
    '--j-color-border': '#cfd3dc',
    '--j-color-border-strong': '#aeb4c0',
    '--j-color-input': '#b8bec9',
    '--j-color-primary': '#3f52c8',
    '--j-color-primary-hover': '#3345b4',
    '--j-color-primary-active': '#293997',
    '--j-color-primary-soft': '#e8eaff',
    '--j-color-secondary': '#525b70',
    '--j-color-secondary-hover': '#424a5d',
    '--j-color-secondary-soft': '#e8eaf0',
    '--j-color-success': '#19764f',
    '--j-color-success-soft': '#e4f5eb',
    '--j-color-info': '#006fa6',
    '--j-color-info-soft': '#e1f3fb',
    '--j-color-warning': '#a65a00',
    '--j-color-warning-soft': '#ffefd1',
    '--j-color-warning-foreground': '#291600',
    '--j-color-danger': '#ba2837',
    '--j-color-danger-soft': '#ffe9ec',
    '--j-color-ring': 'rgb(63 82 200 / 34%)',
    '--j-color-hover-background': '#e7e9ef',
    '--j-color-selected-background': '#e3e6ff',
    '--j-color-disabled-background': '#e9eaf0',
    '--j-color-disabled-text': '#8e939e',
    '--j-overlay-backdrop-bg': 'rgb(19 22 31 / 58%)',
  },
  dark: {
    ...defaultPreset.dark,
    '--j-color-background': '#111318',
    '--j-color-foreground': '#eceef4',
    '--j-color-text-muted': '#b1b5c0',
    '--j-color-text-soft': '#7f8490',
    '--j-color-muted': '#24272f',
    '--j-color-card': '#1b1e25',
    '--j-color-card-foreground': '#eceef4',
    '--j-color-popover': '#22252d',
    '--j-color-popover-foreground': '#eceef4',
    '--j-color-surface-subtle': '#292c35',
    '--j-color-border': '#383c47',
    '--j-color-border-strong': '#555b68',
    '--j-color-input': '#4b515e',
    '--j-color-primary': '#aeb4ff',
    '--j-color-primary-hover': '#c4c8ff',
    '--j-color-primary-active': '#d9dcff',
    '--j-color-primary-soft': '#333768',
    '--j-color-primary-foreground': '#171a45',
    '--j-color-secondary-soft': '#30343e',
    '--j-color-success': '#62d3a0',
    '--j-color-success-soft': '#173d2e',
    '--j-color-info': '#61c7f2',
    '--j-color-info-soft': '#14394b',
    '--j-color-warning': '#ffc568',
    '--j-color-warning-soft': '#493612',
    '--j-color-danger': '#ff8c98',
    '--j-color-danger-soft': '#50272d',
    '--j-color-ring': 'rgb(174 180 255 / 42%)',
    '--j-color-hover-background': '#2d3039',
    '--j-color-selected-background': '#353a69',
    '--j-color-disabled-background': '#292c34',
    '--j-color-disabled-text': '#747985',
    '--j-overlay-backdrop-bg': 'rgb(0 0 0 / 72%)',
    '--j-shadow-xs': '0 1px 2px rgb(0 0 0 / 38%)',
    '--j-shadow-sm': '0 3px 8px rgb(0 0 0 / 42%)',
    '--j-shadow-md': '0 12px 30px rgb(0 0 0 / 48%)',
    '--j-shadow-lg': '0 26px 64px rgb(0 0 0 / 58%)',
  },
  components: {
    ...defaultPreset.components,
    control: {
      ...defaultPreset.components?.['control'],
      '--j-control-height-sm': '2.125rem',
      '--j-control-height-md': '2.625rem',
      '--j-control-height-lg': '3.125rem',
      '--j-control-radius': 'var(--j-radius-sm)',
    },
    button: {
      ...defaultPreset.components?.['button'],
      '--j-button-radius': 'var(--j-radius-sm)',
      '--j-button-font-weight': 'var(--j-font-weight-medium)',
    },
    input: {
      ...defaultPreset.components?.['input'],
      '--j-input-radius': 'var(--j-radius-sm)',
    },
    select: {
      ...defaultPreset.components?.['select'],
      '--j-select-overlay-radius': 'var(--j-radius-md)',
    },
    card: {
      ...defaultPreset.components?.['card'],
      '--j-card-radius': 'var(--j-radius-md)',
      '--j-card-shadow': 'var(--j-shadow-xs)',
    },
    dialog: {
      ...defaultPreset.components?.['dialog'],
      '--j-dialog-radius': 'var(--j-radius-lg)',
      '--j-dialog-shadow': 'var(--j-shadow-lg)',
      '--j-dialog-padding': 'var(--j-spacing-5)',
    },
    scheduler: {
      ...defaultPreset.components?.['scheduler'],
      '--j-scheduler-row-height': '3.5rem',
      '--j-scheduler-drag-shadow': 'var(--j-shadow-md)',
    },
    table: {
      ...defaultPreset.components?.['table'],
      '--j-table-header-bg': 'var(--j-color-surface-subtle)',
      '--j-table-row-hover-bg': 'color-mix(in srgb, var(--j-color-primary) 7%, transparent)',
    },
    navigation: {
      ...defaultPreset.components?.['navigation'],
      '--j-menu-item-height': '2.625rem',
      '--j-tabs-active-indicator-size': '0.1875rem',
    },
    overlay: {
      ...defaultPreset.components?.['overlay'],
      '--j-overlay-radius': 'var(--j-radius-lg)',
    },
    ripple: {
      '--j-ripple-opacity': '0.2',
      '--j-ripple-duration': 'var(--j-duration-slow)',
    },
  },
  aliases: defaultPreset.aliases,
};
