import { JThemePreset } from '../preset.types';
import { defaultPreset } from './default.preset';

/**
 * JRNG's compact professional preset for information-heavy enterprise tools.
 * Density is reduced without reducing the documented minimum target tokens.
 */
export const nexusPreset: JThemePreset = {
  id: 'nexus',
  name: 'nexus',
  displayName: 'Nexus',
  primitive: {
    ...defaultPreset.primitive,
    '--j-font-size-xs': '0.6875rem',
    '--j-font-size-sm': '0.8125rem',
    '--j-font-size-md': '0.9375rem',
    '--j-font-size-lg': '1.0625rem',
    '--j-font-size-xl': '1.25rem',
    '--j-font-weight-medium': '550',
    '--j-font-weight-semibold': '650',
    '--j-line-height-normal': '1.42',
    '--j-line-height-relaxed': '1.55',
    '--j-radius-xs': '0.1875rem',
    '--j-radius-sm': '0.25rem',
    '--j-radius-md': '0.375rem',
    '--j-radius-lg': '0.5rem',
    '--j-radius-xl': '0.625rem',
    '--j-shadow-xs': '0 1px 1px rgb(20 32 48 / 6%)',
    '--j-shadow-sm': '0 1px 3px rgb(20 32 48 / 9%)',
    '--j-shadow-md': '0 7px 18px rgb(20 32 48 / 13%)',
    '--j-shadow-lg': '0 16px 42px rgb(20 32 48 / 18%)',
    '--j-duration-fast': '80ms',
    '--j-duration-normal': '140ms',
    '--j-duration-slow': '220ms',
    '--j-density-gap': 'var(--j-spacing-1)',
    '--j-density-padding': 'var(--j-spacing-2)',
  },
  semantic: {
    ...defaultPreset.semantic,
    '--j-disabled-opacity': '0.56',
  },
  light: {
    ...defaultPreset.light,
    '--j-color-background': '#f3f5f7',
    '--j-color-foreground': '#1d2938',
    '--j-color-text-muted': '#59677a',
    '--j-color-text-soft': '#7c8898',
    '--j-color-muted': '#e9edf1',
    '--j-color-card-foreground': '#1d2938',
    '--j-color-popover-foreground': '#1d2938',
    '--j-color-surface-subtle': '#eef1f4',
    '--j-color-border': '#cbd3dc',
    '--j-color-border-strong': '#aab6c3',
    '--j-color-input': '#bec8d3',
    '--j-color-primary': '#176b87',
    '--j-color-primary-hover': '#115a73',
    '--j-color-primary-active': '#0d475c',
    '--j-color-primary-soft': '#def1f5',
    '--j-color-secondary': '#3f4f63',
    '--j-color-secondary-hover': '#303f51',
    '--j-color-secondary-soft': '#e2e7ec',
    '--j-color-success': '#19704c',
    '--j-color-success-soft': '#e1f3e9',
    '--j-color-info': '#126c9b',
    '--j-color-info-soft': '#e1f1f9',
    '--j-color-warning': '#9b5c05',
    '--j-color-warning-soft': '#fbedcf',
    '--j-color-danger': '#b7323e',
    '--j-color-danger-soft': '#fae7e9',
    '--j-color-ring': 'rgb(23 107 135 / 34%)',
    '--j-color-hover-background': '#e4e9ee',
    '--j-color-selected-background': '#d9edf2',
    '--j-color-disabled-background': '#e7ebef',
    '--j-color-disabled-text': '#8792a0',
    '--j-overlay-backdrop-bg': 'rgb(16 27 41 / 52%)',
  },
  dark: {
    ...defaultPreset.dark,
    '--j-color-background': '#0d141c',
    '--j-color-foreground': '#e7edf3',
    '--j-color-text-muted': '#aab5c0',
    '--j-color-text-soft': '#748190',
    '--j-color-muted': '#1b2631',
    '--j-color-card': '#131e28',
    '--j-color-card-foreground': '#e7edf3',
    '--j-color-popover': '#182530',
    '--j-color-popover-foreground': '#e7edf3',
    '--j-color-surface-subtle': '#202e3a',
    '--j-color-border': '#30404d',
    '--j-color-border-strong': '#4d606e',
    '--j-color-input': '#405362',
    '--j-color-primary': '#67c3dc',
    '--j-color-primary-hover': '#86d3e6',
    '--j-color-primary-active': '#a6e1ed',
    '--j-color-primary-soft': '#16404d',
    '--j-color-primary-foreground': '#062a35',
    '--j-color-secondary-soft': '#263541',
    '--j-color-success': '#57cb92',
    '--j-color-success-soft': '#173c2b',
    '--j-color-info': '#59bde8',
    '--j-color-info-soft': '#15394b',
    '--j-color-warning': '#f2bb58',
    '--j-color-warning-soft': '#493614',
    '--j-color-danger': '#f1848d',
    '--j-color-danger-soft': '#4a282d',
    '--j-color-ring': 'rgb(103 195 220 / 40%)',
    '--j-color-hover-background': '#253440',
    '--j-color-selected-background': '#19434f',
    '--j-color-disabled-background': '#202d38',
    '--j-color-disabled-text': '#697785',
    '--j-overlay-backdrop-bg': 'rgb(2 7 12 / 70%)',
    '--j-shadow-xs': '0 1px 1px rgb(0 0 0 / 28%)',
    '--j-shadow-sm': '0 2px 5px rgb(0 0 0 / 34%)',
    '--j-shadow-md': '0 10px 25px rgb(0 0 0 / 42%)',
    '--j-shadow-lg': '0 22px 54px rgb(0 0 0 / 52%)',
  },
  components: {
    ...defaultPreset.components,
    control: {
      ...defaultPreset.components?.['control'],
      '--j-control-height-sm': '1.75rem',
      '--j-control-height-md': '2.25rem',
      '--j-control-height-lg': '2.625rem',
      '--j-control-padding-x-sm': 'var(--j-spacing-2)',
      '--j-control-padding-x-md': 'var(--j-spacing-3)',
      '--j-control-padding-x-lg': 'var(--j-spacing-4)',
      '--j-control-radius': 'var(--j-radius-sm)',
      '--j-control-min-target': '1.5rem',
    },
    button: {
      ...defaultPreset.components?.['button'],
      '--j-button-radius': 'var(--j-radius-sm)',
      '--j-button-font-weight': 'var(--j-font-weight-semibold)',
    },
    input: {
      ...defaultPreset.components?.['input'],
      '--j-input-radius': 'var(--j-radius-sm)',
    },
    select: {
      ...defaultPreset.components?.['select'],
      '--j-select-overlay-radius': 'var(--j-radius-md)',
      '--j-select-option-height': '2rem',
    },
    card: {
      ...defaultPreset.components?.['card'],
      '--j-card-radius': 'var(--j-radius-md)',
      '--j-card-shadow': 'var(--j-shadow-xs)',
      '--j-card-padding': 'var(--j-spacing-3)',
    },
    dialog: {
      ...defaultPreset.components?.['dialog'],
      '--j-dialog-radius': 'var(--j-radius-lg)',
      '--j-dialog-padding': 'var(--j-spacing-3)',
    },
    table: {
      ...defaultPreset.components?.['table'],
      '--j-table-header-bg': 'var(--j-color-surface-subtle)',
      '--j-table-header-height': '2.375rem',
      '--j-table-filter-row-height': '2.75rem',
      '--j-table-row-height': '2.25rem',
      '--j-table-filter-control-height': '2rem',
      '--j-table-toolbar-height': '2.75rem',
      '--j-table-pagination-height': '2.75rem',
      '--j-table-comfortable-header-height': '2.375rem',
      '--j-table-comfortable-filter-row-height': '2.75rem',
      '--j-table-comfortable-row-height': '2.5rem',
      '--j-table-comfortable-filter-control-height': '2rem',
      '--j-table-comfortable-toolbar-height': '2.75rem',
      '--j-table-comfortable-pagination-height': '2.75rem',
      '--j-table-cell-padding-x': 'var(--j-spacing-3)',
      '--j-table-cell-padding-y': 'var(--j-spacing-1)',
      '--j-table-row-hover-bg': 'color-mix(in srgb, var(--j-color-primary) 6%, transparent)',
    },
    navigation: {
      ...defaultPreset.components?.['navigation'],
      '--j-menu-item-height': '2rem',
      '--j-menu-item-padding-x': 'var(--j-spacing-2)',
      '--j-tabs-height': '2.25rem',
    },
    enterprise: {
      '--j-toolbar-height': '2.5rem',
      '--j-toolbar-padding': 'var(--j-spacing-2)',
      '--j-form-field-gap': 'var(--j-spacing-2)',
      '--j-form-section-gap': 'var(--j-spacing-4)',
      '--j-chip-height': '1.5rem',
      '--j-chip-padding-x': 'var(--j-spacing-2)',
      '--j-kanban-card-padding': 'var(--j-spacing-2)',
      '--j-gantt-row-height': '2rem',
      '--j-scheduler-row-height': '2.25rem',
      '--j-file-browser-row-height': '2rem',
      '--j-query-builder-row-gap': 'var(--j-spacing-2)',
      '--j-filter-toolbar-gap': 'var(--j-spacing-2)',
    },
    overlay: {
      ...defaultPreset.components?.['overlay'],
      '--j-overlay-radius': 'var(--j-radius-md)',
      '--j-overlay-padding': 'var(--j-spacing-2)',
    },
  },
  aliases: defaultPreset.aliases,
};
