export {
  DialogComponent,
  DialogService,
  JDialogComponent,
  JDialogService,
  JrDialogComponent,
  JrDialogService,
  type JDialogCloseReason,
  type JDialogPosition,
  type JDialogSize,
  type JrDialogCloseReason,
  type JrDialogOpenOptions,
  type JrDialogRequest,
  type JrDialogSize,
} from 'jrng-ui';
