// Generated by scripts/generate-demo-sources.mjs. Do not edit manually.
export const demoSources = {
  'avatar-zoom-demo': {
    html: '<div class="profile">\r\n  <j-avatar image="/assets/avatars/avery.svg" label="Avery Reed" size="lg" previewable />\r\n  <div><strong>Avery Reed</strong><span>Product designer</span></div>\r\n</div>\r\n',
    ts: "import { Component } from '@angular/core';\r\nimport { JAvatarComponent } from 'jrng-ui/avatar';\r\n\r\n@Component({\r\n  selector: 'app-avatar-zoom-demo',\r\n  imports: [JAvatarComponent],\r\n  templateUrl: './avatar-zoom-demo.component.html',\r\n  styleUrl: './avatar-zoom-demo.component.scss',\r\n})\r\nexport class AvatarZoomDemoComponent {}\r\n",
    scss: '.profile {\r\n  align-items: center;\r\n  display: flex;\r\n  gap: var(--j-spacing-md);\r\n}\r\n.profile div {\r\n  display: grid;\r\n  gap: var(--j-spacing-xs);\r\n}\r\n.profile span {\r\n  color: var(--j-color-muted-foreground);\r\n}\r\n',
  },
  'button-basic-demo': {
    html: '<div class="demo-row">\r\n  <j-button label="Apply updates" icon="save" (onClick)="save()" />\r\n  @if (saved) {\r\n    <span role="status">Changes saved.</span>\r\n  }\r\n</div>\r\n',
    ts: "import { Component } from '@angular/core';\r\nimport { JButtonComponent } from 'jrng-ui/button';\r\n\r\n@Component({\r\n  selector: 'app-button-basic-demo',\r\n  imports: [JButtonComponent],\r\n  templateUrl: './button-basic-demo.component.html',\r\n  styleUrl: './button-basic-demo.component.scss',\r\n})\r\nexport class ButtonBasicDemoComponent {\r\n  saved = false;\r\n  save(): void {\r\n    this.saved = true;\r\n  }\r\n}\r\n",
    scss: '.demo-row {\r\n  align-items: center;\r\n  display: flex;\r\n  flex-wrap: wrap;\r\n  gap: var(--j-spacing-md);\r\n}\r\n',
  },
  'card-metric-demo': {
    html: '<j-card header="Monthly revenue" subheader="Compared with last month">\r\n  <div class="metric-row">\r\n    <strong>{{ revenue }}</strong>\r\n    <j-badge value="+12.4%" severity="success" />\r\n  </div>\r\n  <j-progress-bar [value]="targetProgress" label="72% of target" />\r\n</j-card>\r\n',
    ts: "import { Component } from '@angular/core';\r\nimport { JBadgeComponent } from 'jrng-ui/badge';\r\nimport { JCardComponent } from 'jrng-ui/card';\r\nimport { JProgressBarComponent } from 'jrng-ui/progress-bar';\r\n\r\n@Component({\r\n  selector: 'app-card-metric-demo',\r\n  imports: [JBadgeComponent, JCardComponent, JProgressBarComponent],\r\n  templateUrl: './card-metric-demo.component.html',\r\n  styleUrl: './card-metric-demo.component.scss',\r\n})\r\nexport class CardMetricDemoComponent {\r\n  readonly revenue = '$84,250';\r\n  readonly targetProgress = 72;\r\n}\r\n",
    scss: '.metric-row {\r\n  align-items: center;\r\n  display: flex;\r\n  gap: var(--j-spacing-md);\r\n}\r\n.metric-row strong {\r\n  font-size: var(--j-font-size-3xl);\r\n}\r\n',
  },
  'loader-types-demo': {
    html: '<div class="loader-grid">\r\n  <j-loader type="spinner" label="Loading report" />\r\n  <j-loader type="dots" label="Loading messages" />\r\n  <j-loader type="bars" label="Syncing records" />\r\n  <j-loader type="ring" [value]="68" label="68 percent complete" />\r\n</div>\r\n',
    ts: "import { Component } from '@angular/core';\r\nimport { JLoaderComponent } from 'jrng-ui/loader';\r\n\r\n@Component({\r\n  selector: 'app-loader-types-demo',\r\n  imports: [JLoaderComponent],\r\n  templateUrl: './loader-types-demo.component.html',\r\n  styleUrl: './loader-types-demo.component.scss',\r\n})\r\nexport class LoaderTypesDemoComponent {}\r\n",
    scss: '.loader-grid {\r\n  align-items: center;\r\n  display: flex;\r\n  flex-wrap: wrap;\r\n  gap: var(--j-spacing-xl);\r\n}\r\n',
  },
  'text-expand-basic-demo': {
    html: '<j-text-expand [text]="description" [collapsedLength]="100" />\r\n',
    ts: "import { Component } from '@angular/core';\r\nimport { JTextExpandComponent } from 'jrng-ui/text-expand';\r\n\r\n@Component({\r\n  selector: 'app-text-expand-basic-demo',\r\n  imports: [JTextExpandComponent],\r\n  templateUrl: './text-expand-basic-demo.component.html',\r\n  styleUrl: './text-expand-basic-demo.component.scss',\r\n})\r\nexport class TextExpandBasicDemoComponent {\r\n  readonly description =\r\n    'A durable task light with adjustable brightness, a compact base, and a warm reading mode for desks and bedside tables. The metal arm rotates smoothly and the controls remain easy to reach.';\r\n}\r\n",
    scss: ':host {\r\n  display: block;\r\n  max-width: 36rem;\r\n}\r\n',
  },
} as const;
