// Generated by scripts/generate-demo-sources.mjs. Do not edit manually.
export const demoSources = {
  'avatar-zoom-demo': {
    html: '<div class="profile">\n  <j-avatar image="/assets/avatars/avery.svg" label="Avery Reed" size="lg" previewable />\n  <div><strong>Avery Reed</strong><span>Product designer</span></div>\n</div>\n',
    ts: "import { Component } from '@angular/core';\nimport { JAvatarComponent } from 'jrng-ui/avatar';\n\n@Component({\n  selector: 'app-avatar-zoom-demo',\n  imports: [JAvatarComponent],\n  templateUrl: './avatar-zoom-demo.component.html',\n  styleUrl: './avatar-zoom-demo.component.scss',\n})\nexport class AvatarZoomDemoComponent {}\n",
    scss: '.profile {\n  align-items: center;\n  display: flex;\n  gap: var(--j-spacing-md);\n}\n.profile div {\n  display: grid;\n  gap: var(--j-spacing-xs);\n}\n.profile span {\n  color: var(--j-color-muted-foreground);\n}\n',
  },
  'button-basic-demo': {
    html: '<div class="demo-row">\n  <j-button label="Save changes" icon="save" (onClick)="save()" />\n  @if (saved) {\n    <span role="status">Changes saved.</span>\n  }\n</div>\n',
    ts: "import { Component } from '@angular/core';\nimport { JButtonComponent } from 'jrng-ui/button';\n\n@Component({\n  selector: 'app-button-basic-demo',\n  imports: [JButtonComponent],\n  templateUrl: './button-basic-demo.component.html',\n  styleUrl: './button-basic-demo.component.scss',\n})\nexport class ButtonBasicDemoComponent {\n  saved = false;\n  save(): void {\n    this.saved = true;\n  }\n}\n",
    scss: '.demo-row {\n  align-items: center;\n  display: flex;\n  flex-wrap: wrap;\n  gap: var(--j-spacing-md);\n}\n',
  },
  'card-metric-demo': {
    html: '<j-card header="Monthly revenue" subheader="Compared with last month">\n  <div class="metric-row">\n    <strong>{{ revenue }}</strong>\n    <j-badge value="+12.4%" severity="success" />\n  </div>\n  <j-progress-bar [value]="targetProgress" label="72% of target" />\n</j-card>\n',
    ts: "import { Component } from '@angular/core';\nimport { JBadgeComponent } from 'jrng-ui/badge';\nimport { JCardComponent } from 'jrng-ui/card';\nimport { JProgressBarComponent } from 'jrng-ui/progress-bar';\n\n@Component({\n  selector: 'app-card-metric-demo',\n  imports: [JBadgeComponent, JCardComponent, JProgressBarComponent],\n  templateUrl: './card-metric-demo.component.html',\n  styleUrl: './card-metric-demo.component.scss',\n})\nexport class CardMetricDemoComponent {\n  readonly revenue = '$84,250';\n  readonly targetProgress = 72;\n}\n",
    scss: '.metric-row {\n  align-items: center;\n  display: flex;\n  gap: var(--j-spacing-md);\n}\n.metric-row strong {\n  font-size: var(--j-font-size-3xl);\n}\n',
  },
  'loader-types-demo': {
    html: '<div class="loader-grid">\n  <j-loader type="spinner" label="Loading report" />\n  <j-loader type="dots" label="Loading messages" />\n  <j-loader type="bars" label="Syncing records" />\n  <j-loader type="ring" [value]="68" label="68 percent complete" />\n</div>\n',
    ts: "import { Component } from '@angular/core';\nimport { JLoaderComponent } from 'jrng-ui/loader';\n\n@Component({\n  selector: 'app-loader-types-demo',\n  imports: [JLoaderComponent],\n  templateUrl: './loader-types-demo.component.html',\n  styleUrl: './loader-types-demo.component.scss',\n})\nexport class LoaderTypesDemoComponent {}\n",
    scss: '.loader-grid {\n  align-items: center;\n  display: flex;\n  flex-wrap: wrap;\n  gap: var(--j-spacing-xl);\n}\n',
  },
  'text-expand-basic-demo': {
    html: '<j-text-expand [text]="description" [collapsedLength]="100" />\n',
    ts: "import { Component } from '@angular/core';\nimport { JTextExpandComponent } from 'jrng-ui/text-expand';\n\n@Component({\n  selector: 'app-text-expand-basic-demo',\n  imports: [JTextExpandComponent],\n  templateUrl: './text-expand-basic-demo.component.html',\n  styleUrl: './text-expand-basic-demo.component.scss',\n})\nexport class TextExpandBasicDemoComponent {\n  readonly description =\n    'A durable task light with adjustable brightness, a compact base, and a warm reading mode for desks and bedside tables. The metal arm rotates smoothly and the controls remain easy to reach.';\n}\n",
    scss: ':host {\n  display: block;\n  max-width: 36rem;\n}\n',
  },
} as const;
